---
#Set up here some Nicknames
nicknames:
  - CoolPlayer123
  - ProGamer2000
  - NinjaMaster
  - AwesomeDude
  - SuperStar
  - MysteryPlayer
  - GamerGirl87
  - PixelNinja
  - LegendKiller
...